package_monitor/urls.py
"""Urls for Package Monitor."""

from django.urls import path

from . import views

app_name = "package_monitor"

urlpatterns = [
    path("", views.index, name="index"),
    path("package_list_data", views.package_list_data, name="package_list_data"),
    path(
        "refresh_distributions",
        views.refresh_distributions,
        name="refresh_distributions",
    ),
]

package_monitor/models.py
"""Models for Package Monitor."""

from django.db import models

from .managers import DistributionManager

MAX_LENGTH_VERSION_STRING = 64


class General(models.Model):
    """Meta model for app permissions"""

    class Meta:
        managed = False
        default_permissions = ()
        permissions = (("basic_access", "Can access this app"),)


class Distribution(models.Model):
    """A Python distribution package"""

    name = models.CharField(
        max_length=255, unique=True, help_text="Name of this package"
    )
    description = models.TextField(default="", help_text="Description of this package")
    apps = models.JSONField(
        default=list,
        help_text="List of installed Django apps included in this package",
    )
    has_installed_apps = models.BooleanField(
        default=False,
        help_text="Whether this package has installed Django apps",
    )
    used_by = models.JSONField(
        default=list,
        help_text="List of other distribution packages using this package",
    )
    installed_version = models.CharField(
        max_length=MAX_LENGTH_VERSION_STRING,
        default="",
        help_text="Currently installed version of this package",
    )
    latest_version = models.CharField(
        max_length=MAX_LENGTH_VERSION_STRING,
        default="",
        help_text="Latest version available for this package",
    )
    latest_notified_version = models.CharField(
        max_length=MAX_LENGTH_VERSION_STRING,
        default="",
        help_text="Latest version that has been notified",
    )
    is_outdated = models.BooleanField(
        default=None,
        null=True,
        help_text="A package is outdated when there is a newer stable version available",
    )
    is_editable = models.BooleanField(
        default=None,
        null=True,
        help_text="Package has been installed in editable mode, i.e. pip install -e",
    )
    website_url = models.TextField(
        default="", help_text="URL to the home page of this package"
    )
    updated_at = models.DateTimeField(
        auto_now=True, help_text="Date & time this data was last updated"
    )

    objects = DistributionManager()

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs):
        self.calc_has_installed_apps()
        super().save(*args, **kwargs)

    def calc_has_installed_apps(self) -> None:
        """Calculate if this distribution has apps."""
        self.has_installed_apps = bool(self.apps)

    @property
    def pip_install_version(self) -> str:
        """Return string for pip installing the latest version of this package."""
        return (
            f"{self.name}=={self.latest_version}" if self.latest_version else self.name
        )

package_monitor/views.py
"""Views for Package Monitor."""

from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _

from app_utils.views import link_html, yesnonone_str

from . import __title__
from .app_settings import (
    PACKAGE_MONITOR_INCLUDE_PACKAGES,
    PACKAGE_MONITOR_SHOW_ALL_PACKAGES,
)
from .models import Distribution

PACKAGE_LIST_FILTER_PARAM = "filter"


@login_required
@permission_required("package_monitor.basic_access")
def index(request):
    """Main view."""
    obj = Distribution.objects.first()
    updated_at = obj.updated_at if obj else None
    distributions_qs = Distribution.objects.filter_visible()
    my_filter = request.GET.get(PACKAGE_LIST_FILTER_PARAM)
    if not my_filter:
        app_count = Distribution.objects.filter_visible().outdated_count()
        my_filter = "outdated" if app_count and app_count > 0 else "current"
    outdated_install_command = (
        Distribution.objects.filter_visible()
        .filter(is_outdated=True)
        .order_by("name")
        .build_install_command()
    )
    context = {
        "app_title": __title__,
        "page_title": _("Distribution packages"),
        "updated_at": updated_at,
        "filter": my_filter,
        "all_count": distributions_qs.count(),
        "current_count": distributions_qs.filter(is_outdated=False).count(),
        "outdated_count": distributions_qs.outdated_count(),
        "unknown_count": distributions_qs.filter(is_outdated__isnull=True).count(),
        "include_packages": PACKAGE_MONITOR_INCLUDE_PACKAGES,
        "show_all_packages": PACKAGE_MONITOR_SHOW_ALL_PACKAGES,
        "outdated_install_command": outdated_install_command,
    }
    return render(request, "package_monitor/index.html", context)


@login_required
@permission_required("package_monitor.basic_access")
def package_list_data(request) -> JsonResponse:
    """Return the packages as list in JSON.
    Specify different subsets with the "filter" GET parameter
    """
    my_filter = request.GET.get(PACKAGE_LIST_FILTER_PARAM, "")
    distributions_qs = Distribution.objects.filter_visible()
    if my_filter == "outdated":
        distributions_qs = distributions_qs.filter(is_outdated=True)
    elif my_filter == "current":
        distributions_qs = distributions_qs.filter(is_outdated=False)
    elif my_filter == "unknown":
        distributions_qs = distributions_qs.filter(is_outdated__isnull=True)

    data = []
    for dist in distributions_qs.order_by("name"):
        dist: Distribution
        name_link_html = (
            link_html(dist.website_url, dist.name) if dist.website_url else dist.name
        )
        if dist.is_outdated:
            name_link_html += (
                '&nbsp;<i class="fas fa-exclamation-circle" '
                f'title="{_("Update available")}"></i>'
            )

        if dist.apps:
            _lst = list(dist.apps)
            apps_html = "<br>".join(_lst) if _lst else "-"
        else:
            apps_html = ""

        if dist.used_by:
            used_by_sorted = sorted(dist.used_by, key=lambda k: k["name"])
            used_by_html = "<br>".join(
                [
                    format_html(
                        '<span title="{}" class="text-nowrap;">{}</span>',
                        (
                            ", ".join(row["requirements"])
                            if row["requirements"]
                            else "ANY"
                        ),
                        (
                            link_html(row["homepage_url"], row["name"])
                            if row["homepage_url"]
                            else row["name"]
                        ),
                    )
                    for row in used_by_sorted
                ]
            )
        else:
            used_by_html = ""

        if not dist.latest_version:
            latest_html = "?"
        else:
            command = f"pip install {dist.pip_install_version}"
            latest_html = (
                f'<span class="copy_to_clipboard" '
                f'title="{command}"'
                f' data-clipboard-text="{command}">'
                f"{dist.latest_version}"
                '&nbsp;&nbsp;<i class="far fa-copy"></i></span>'
            )

        description = dist.description
        if dist.is_editable:
            description += f" [{_('EDITABLE')}]"
        data.append(
            {
                "name": dist.name,
                "name_link": name_link_html,
                "apps": apps_html,
                "used_by": used_by_html,
                "current": dist.installed_version,
                "latest": latest_html,
                "is_outdated": dist.is_outdated,
                "is_outdated_str": yesnonone_str(dist.is_outdated),
                "description": description,
            }
        )

    return JsonResponse(data, safe=False)


@login_required
@permission_required("package_monitor.basic_access")
def refresh_distributions(request):
    """Ajax view for refreshing all distributions."""
    Distribution.objects.update_all()
    return HttpResponse("ok")

package_monitor/templates/package_monitor/base.html
{% extends 'allianceauth/base-bs5.html' %}
{% load humanize %}
{% load i18n %}

{% block page_title %}{{ app_title }}{% endblock %}

{% block header_nav_brand %}{{ app_title }}{% endblock %}

{% block content %}
    {% include "framework/header/page-header.html" with title=page_title %}

    {% block details %}{% endblock %}
{% endblock %}

package_monitor/templates/package_monitor/index.html
{% extends "package_monitor/base.html" %}

{% load humanize %}
{% load i18n %}
{% load static %}

{% block details %}
    <!-- Modal for Refreshing Distributions -->
    <div class="modal fade" id="modalRefreshingDistributions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title fs-5">
                        {% translate "Refreshing distributions" %}
                    </div>

                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}"></button>
                </div>

                <div class="modal-body">
                    <p>
                        {% blocktranslate %}
                            Refreshing data for approx. {{ all_count }} distributions...
                        {% endblocktranslate %}
                    </p>

                    <div id="modalLoadInfo">
                        {% if NIGHT_MODE %}
                            <img
                                    src="{% static 'package_monitor/images/Spinner-1s-64px-dark.gif' %}"
                                    alt="Loading Data"
                            >
                        {% else %}
                            <img
                                    src="{% static 'package_monitor/images/Spinner-1s-64px-light.gif' %}"
                                    alt="Loading Data"
                            >
                        {% endif %}

                        <p class="text-muted"></p>
                    </div>

                    <div id="modalLoadError"></div>
                </div>
            </div>
        </div>
    </div>

    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item">
            <a class="nav-link{% if filter != 'current' and filter != 'outdated' and filter != 'unknown' %} active{% endif %}" href="{% url 'package_monitor:index' %}?filter=all">
                {% translate "All" %}&nbsp;({{ all_count|default:"-" }})
            </a>
        </li>
        <li role="presentation" class="nav-item">
            <a class="nav-link{% if filter == 'current' %} active{% endif %}" href="{% url 'package_monitor:index' %}?filter=current">
                {% translate "Current" %}&nbsp;({{ current_count|default:"-" }})
            </a>
        </li>
        <li role="presentation" class="nav-item">
            <a class="nav-link{% if filter == 'outdated' %} active{% endif %}" href="{% url 'package_monitor:index' %}?filter=outdated">
                {% translate "Update available" %}&nbsp;({{ outdated_count|default:"-" }})
            </a>
        </li>
        <li role="presentation" class="me-auto nav-item">
            <a class="nav-link{% if filter == 'unknown' %} active{% endif %}"  class="dotted_underline"
                href="{% url 'package_monitor:index' %}?filter=unknown"
                title="{% translate 'No information about new release available on PyPI' %}">
                {% translate 'No Info' %}&nbsp;({{ unknown_count|default:"-" }})
            </a>
        </li>
        <li role="presentation" class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">
                    {% translate "not yet" as never_text %}
                    {% translate 'Last updated' %} {{ updated_at|naturaltime|default_if_none:never_text }}&nbsp;&nbsp;
                </a>
        </li>
        <li role="presentation" class="nav-item">
                <a
                    class="btn btn-success"
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#modalRefreshingDistributions"
                    title="{% translate 'Refresh data now' %}">
                    <i class="fas fa-sync"></i>
                </a>
        </li>
    </ul>

    <div class="card card-default card-tabs tab-content border-0">
        <div class="card-body">
            <div class="table-responsive mb-3">
                <table id="tab_package_list" class="table table-striped w-100">
                    <thead>
                        <tr>
                            <th
                                class="dotted_underline"
                                title="{% translate 'Name of this distribution package' %}">
                                {% translate "Name" %}
                            </th>
                            <th
                                class="dotted_underline"
                                title="{% translate 'Currently installed version of this package' %}">
                                {% translate "Installed" %}
                            </th>
                            <th
                                class="dotted_underline"
                                title="{% translate 'Latest available stable version compliant with all requirements for this package' %}">
                                {% translate "Latest" %}
                            </th>
                            <th>{% translate "Description" %}</th>
                            <th
                                class="dotted_underline"
                                title="{% translate 'Currently installed Django apps included in this package' %}">
                                {% translate "Included Apps" %}
                            </th>
                            <th
                                class="dotted_underline"
                                title="{% translate 'Other distribution packages that are using this package' %}">
                                {% translate "Used By" %}
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>

            <p class="text-muted">
                {% if show_all_packages %}
                    {% translate "Shows all known distribution packages." %}
                {% else %}
                    {% translate "Shows only distribution packages that contain an installed Django app." %}

                    {% if include_packages %}
                        {% translate "In addition these packages are shown:" %} {{ include_packages|join:", " }}
                    {% endif%}
                {% endif%}
                <br>
                {% blocktranslate %}
                    The latest stable of a package is retrieved from PyPI.
                    Will show as "?" if PyPI has no info about a package.
                {% endblocktranslate %}
            </p>

            {% if outdated_count %}
                <p
                    class="copy_to_clipboard"
                    data-clipboard-text="{{ outdated_install_command }}"
                    title="{{ outdated_install_command }}"
                >
                    {% blocktranslate %}
                        Command for installing all {{ outdated_count }} outdated packages
                    {% endblocktranslate %}
                    &nbsp;&nbsp;
                    <i class="far fa-copy"></i>
                </p>
            {% else %}
                <p class="text-muted">{% translate "No outdated packages to install." %}</p>
            {% endif %}
        </div>
    </div>
{% endblock details %}

{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/clipboard-js.html" %}

    <script>
        /* global ClipboardJS */

        /** Copy given text to the clipboard */
        const clipboard = new ClipboardJS('.copy_to_clipboard');

        clipboard.on('success', (e) => {
            e.clearSelection();
        });

        clipboard.on('error', (e) => {
            console.error('Action:', e.action);
            console.error('Trigger:', e.trigger);
        });

        $(document).ready(() => {
            /* dataTable def */
            $('#tab_package_list').DataTable({
                ajax: {
                    url: '{% url "package_monitor:package_list_data" %}?filter={{ filter }}',
                    dataSrc: '',
                    cache: false
                },

                columns: [
                    { data: 'name_link' },
                    { data: 'current' },
                    { data: 'latest' },
                    { data: 'description' },
                    { data: 'apps' },
                    { data: 'used_by' }
                ],

                ordering: false,
                info: false,

                columnDefs: [
                    { 'sortable': false, 'targets': [0, 1, 2, 3, 4] },
                ],

                paging: false,

                rowCallback: (row, data, index) => {
                    if (data['is_outdated']) {
                        $(row).find('td:eq(1)').addClass('table-warning')
                        $(row).find('td:eq(2)').addClass('table-warning')
                        $(row).find('td:eq(2)').css('font-weight', 'bold')
                    }
                }
            });

            $('#modalRefreshingDistributions').on('show.bs.modal', (event) => {
                $('#modalLoadError').html('');
                $('#modalLoadInfo').show();

                $.get('{% url "package_monitor:refresh_distributions" %}')
                    .done(() => {
                        window.location.reload(true);
                    })
                    .fail(( jqXHR ) => {
                        $('#modalLoadInfo').hide();
                        console.log(jqXHR);
                        $('#modalLoadError').html(
                            '<p class="text-danger">An unexpected error occurred: '
                            + jqXHR.status
                            + ' '
                            + jqXHR.statusText
                            + '</p><p class="text-danger">'
                            + 'Please close this window and try again.</p>'
                        );
                    });
            })
        });
    </script>
{% endblock extra_javascript %}

{% block extra_css %}
    {% include 'bundles/datatables-css-bs5.html' %}

    <link rel="stylesheet" href="{% static 'package_monitor/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'package_monitor/css/package_list.css' %}">
{% endblock extra_css %}